Compatiable with Laravel 7 MigrationCreator construct
laravel-admin-extensions/helpers pull request #30
Opened 2020-05-24 15:57 UTC by virutmath

2020-07-30 04:57 UTC, czhou commented
Is there any plan to merge this pr please? cause this issue breaks helpers on Laravel 7.

2020-08-12 08:32 UTC, hanody968 commented
Free Nice

2020-10-08 18:26 UTC, themightysapien commented
Why is it not merged yet ??

2021-10-11 09:40 UTC, jxlwqq requested changes

2021-10-11 09:40 UTC, jxlwqq commented on composer.json
> +        "encore/laravel-admin": "~1.6 || dev-hq_ems"
```suggestion
        "encore/laravel-admin": "~1.6"
```

2021-10-11 09:41 UTC, jxlwqq approved these changes

2021-10-11 09:41 UTC, merged

2021-10-11 09:41 UTC, jxlwqq commented
thanks.